### PR TITLE
Update shariff-flipboard.php

### PR DESCRIPTION
**Pull request by Ensam57**

### CODE REVIEW

**Comment by 3UU** [comment]
The default fall back is ever the english term. So it makes no sense for me to add a word that is the same like in the English version. With complete phrases perhaps there would a reason if because of grammar the string could have different positions or get extensions. But for a single word that is the same we should not extend the code.

**Comment by InfoLibre** [comment]
Yes, but even the english word isn't set. Could you let it in all the ticket I did and you closed?

**Comment by InfoLibre** [comment]
```
// Button text label.
	$button_text_array = array(
		'en' => 'Flipboard',
	);
```

**Comment by InfoLibre** [comment]
If you don't add this code, there's no fall back.
See https://github.com/3UU/wordpress-shariff-wrapper/blob/master/shariff/services/shariff-mailto.php too.

**Comment by 3UU** [comment]
Hm, you are right. We need at least the english word ;-) Reopen. We have an closer look on this next weekend.

**Comment by 3UU** [comment]
Same as with https://github.com/3UU/wordpress-shariff-wrapper/pull/150

**Pull request closed without merging**
