### PR TITLE
Update shariff-vk.php

### PR DESCRIPTION
**Pull request by Ensam57**
Add Button text label

### CODE REVIEW

**Comment by 3UU** [comment]
We do not want change the terms used on so much sites since years. We are thinking about an option to change the button layout/naming within the themes directory. So that everybody can change it with no fear of the next plugin update ;-) But this solution will need some time to develop/test. However please feel free to send a request that follows this way.

**Comment by Ensam57** [comment]
I don't understand why you don't want to add this code. It's already added in others buttons and works perfectly. It's a good solution to give a name to buttons.

**Comment by Ensam57** [comment]
See https://github.com/3UU/wordpress-shariff-wrapper/blob/master/shariff/services/shariff-mailto.php

**Comment by Ensam57** [comment]
I'm sure the 50 000 other users will be happy to see the name of each button near logo and not "share" everybody. All buttons are sharing buttons, you don't need to write it, all users know this.

**Comment by Ensam57** [comment]
image

**Comment by Ensam57** [comment]
image

**Comment by Ensam57** [comment]
Text can be in code and not in theme. Theme should contain only CSS, not text.

**Comment by 3UU** [comment]
My last: We should find a solution that enables users to change it "update save" outside the plugins directory. We do _not_ want change the look of tausends of websites with a plugin update. BTW: With theme I mean the WP themes. Because on many hosted WP sites the owner is not able to do changes within the plugin directory. But they can change the content within the "theme". You are right, that these labels are simple text in code. But not text in the meaning of an CMS! So either we put this button labels into the database... and get an horrible confusing admin menu. Or we use the themes that WP offers. Or we find a better solution :-)

**Pull request closed without merging**
