### PR TITLE
better experience with small round buttons

### PR DESCRIPTION
**Pull request by timse201**
the small round buttons are too small for some fingers on smartphones
there could be some false clicks on the wrong share button
to prevent this we could add some more space between the buttons

### CODE REVIEW

**Comment by startef** [comment]
That is good suggestion, thank you!

We just need to tweak your solution a bit in order to make sure that:
- only small buttons are affected, not all sizes
- the margin is not being added on vertical orientation
- the margin is not applied to the first and last element, because that would mess up the alignment

**Comment by timse201** [comment]
could be that we can do the 3. point by just using padding left/right with -2px in the ul element but didnt test it now

**Comment by startef** [comment]
I'll test it at the weekend and will include it in the next release round. Thank you!

**Comment by timse201** [comment]
bumb ;)

**Comment by 3UU** [comment]
done in newer version

**Pull request closed without merging**
